name : Python CI

on : [push]

jobs: 
  build :
     runs-on: ubuntu-latest
     strategy : 
        matrix : 
           python-version : ["3.7", "3.8", "3.9", "3.10"]
     steps: 
        - uses : actions/checkout@v3
        - name : setup python with ${{matrix.python-version}}
        - uses : actions/setup-python@v4
          with : 
              python-version : ${{matrix.python-version}}
        - name : install dependencies 
          run : |
              python -m pip install --upgrade pip
              pip install flake8 pytest
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
        - name: Test with pytest
          run : |
                pytest
         

  
