name : Python CI

on : [push]

jobs: 
  build :
     runs-on: ubuntu-latest
     strategy : 
        matrix : 
           python-version : ["3.7", "3.8", "3.9", "3.10"]
     steps: 
        - uses : actions/checkout@v3
        - name : setup python with ${{matrix.python-version}}
        - uses : actions/setup-python@v4
          with : 
              python-version : ${{matrix.python-version}}
        - name : install dependencies 
          run : |
              python -m pip install --upgrade pip
              pip install flake8 pytest
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
        - name: Lint with flake8
          run: |
              # stop the build if there are Python syntax errors or undefined names
              flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
              # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        - name: Test with pytest
          run : |
                pytest
         

  
